[env:heltec_v4_diag]
platform = espressif32 @ 6.12.0
board = heltec_v4
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 921600
board_build.variants_dir = variants
build_flags =
  -D CORE_DEBUG_LEVEL=0
lib_deps =
  jgromes/RadioLib @ ^7.3.0
